---
- name: check if ceph deployment previously completed
  stat:
    path: /home/ceph-deploy/cluster/ceph-deploy.done
  register: stat_result

- import_tasks: ceph_install.yml
  when: stat_result.stat.exists == False

- import_tasks: ceph_install_deploy.yml
  become: yes
  become_user: ceph-deploy
  vars:
    ceph_deploy_opts: --username ceph-deploy
  when: stat_result.stat.exists == False

- name: ceph deployment complete
  file:
    path: /home/ceph-deploy/cluster/ceph-deploy.done
    state: touch
    mode: 0644
  when: stat_result.stat.exists == False

- import_tasks: ceph_eucalyptus.yml
