---
- name: install midonet nsdb dependency packages
  yum:
    name:
      - dsc22
      - java-1.8.0-openjdk-headless
      - zkdump
      - zookeeper
    state: present
  tags:
    - image
    - packages

- name: create cassandra tmpfiles configuration
  copy:
    content: |
      # path                       mode uid       gid       age
      d /run/cassandra             0755 cassandra cassandra -
    dest: /etc/tmpfiles.d/cassandra.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - image

- name: cassandra systemd drop-in directory
  file:
    path: /etc/systemd/system/cassandra.service.d
    state: directory
    mode: 0755

- name: cassandra systemd drop-in for heap configuration
  copy:
    dest: /etc/systemd/system/cassandra.service.d/jvmheap.conf
    mode: 0644
    content: |
      [Service]
      Environment="MAX_HEAP_SIZE={{ midonet_cassandra_heap | default(midonet_cassandra_heapnew) }}" "HEAP_NEWSIZE={{ midonet_cassandra_heapnew | default(midonet_cassandra_heap) }}"
  when: midonet_cassandra_heap is not none or midonet_cassandra_heapnew is not none

- name: cassandra configure cluster name
  replace:
    path: /etc/cassandra/conf/cassandra.yaml
    regexp: '^cluster_name: .+$'
    replace: "cluster_name: {{ midonet_cassandra_name }}"

- name: cassandra configure listen address
  replace:
    path: /etc/cassandra/conf/cassandra.yaml
    regexp: '^listen_address: .+$'
    replace: "listen_address: {{ eucalyptus_host_cluster_ipv4 }}"

- name: cassandra configure rpc listen address
  replace:
    path: /etc/cassandra/conf/cassandra.yaml
    regexp: '^rpc_address: .+$'
    replace: "rpc_address: {{ eucalyptus_host_cluster_ipv4 }}"

- name: cassandra configure seeds
  replace:
    path: /etc/cassandra/conf/cassandra.yaml
    regexp: '^(\s+)-\s+seeds:\s+.+$'
    replace: '\1- seeds: "{{ groups.midonet_nsdb | map("extract", hostvars, ["eucalyptus_host_cluster_ipv4"]) | list | join(",") }}"'

- name: start cassandra service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: cassandra

- name: set zookeeper server id fact
  set_fact:
    eucalyptus_zookeeper_server_id: "{{ zookeeper_server_id | default(eucalyptus_host_cluster_ipv4) | regex_replace('^.*\\.(\\d+)$', '\\1') }}"

- name: zookeeper server id
  copy:
    dest: /var/lib/zookeeper/myid
    owner: zookeeper
    group: zookeeper
    mode: 0644
    content: "{{ eucalyptus_zookeeper_server_id }}"

- name: zookeeper configure servers
  blockinfile:
    path: /etc/zookeeper/zoo.cfg
    marker: '# {mark} midonet nsdb zookeeper server {{ hostvars[item].eucalyptus_zookeeper_server_id }} configuration'
    block: "server.{{ hostvars[item].eucalyptus_zookeeper_server_id }}={{ hostvars[item].eucalyptus_host_cluster_ipv4 }}:2888:3888"
  with_items: "{{ groups.midonet_nsdb }}"

- name: zookeeper configure autopurge snap count
  replace:
    path: /etc/zookeeper/zoo.cfg
    regexp: '^#?autopurge.snapRetainCount=.+$'
    replace: 'autopurge.snapRetainCount=3'

- name: zookeeper configure autopurge interval
  replace:
    path: /etc/zookeeper/zoo.cfg
    regexp: '^#?autopurge.purgeInterval=.+$'
    replace: 'autopurge.purgeInterval=1'

- name: zookeeper configure listen address
  lineinfile:
    dest: /etc/zookeeper/zoo.cfg
    state: present
    regexp: '^clientPortAddress=.+$'
    line: "clientPortAddress={{ eucalyptus_host_cluster_ipv4 }}"
    insertafter: '^clientPort=.+$'

- name: zookeeper systemd drop-in directory
  file:
    path: /etc/systemd/system/zookeeper.service.d
    state: directory
    mode: 0755
  tags:
    - image

- name: zookeeper systemd drop-in for disabling jmx listener
  copy:
    dest: /etc/systemd/system/zookeeper.service.d/jmxdisable.conf
    mode: 0644
    content: |
      [Service]
      Environment=JMXDISABLE=true
  tags:
    - image

- name: zookeeper systemd drop-in for heap configuration
  copy:
    dest: /etc/systemd/system/zookeeper.service.d/jvmheap.conf
    mode: 0644
    content: |
      [Service]
      Environment="JVMFLAGS=-Xmx{{ midonet_zookeeper_heap }} -Xms{{ midonet_zookeeper_heap }}"
  when: midonet_zookeeper_heap is not none

- name: start zookeeper service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: zookeeper

- name: wait for zookeeper service
  wait_for:
    sleep: 10
    host: "{{ eucalyptus_host_cluster_ipv4 }}"
    port: 2181
    timeout: 120

