---
# Example inventory for localhost cloud-in-a-box installs
#
# ansible-playbook \
#   --extra-vars cloud_instances_state_dir=/home/eucalyptus/instances \
#   --extra-vars cloud_instances_conf_work_size=21000 \
#   --inventory inventory_example_local.yml \
#   playbook_vpcmido.yml
#

all:
  hosts:
    ciab:
      ansible_connection: local
      host_public_ipv4: "{{ cloud_address }}"
      host_cluster_ipv4: "{{ cloud_address }}"
  vars:
    cloud_address: "{{ ansible_default_ipv4.address }}"
    cloud_system_dns_dnsdomain: "ciab-{{ cloud_address|replace('.', '-') }}.euca.me"
    
    # Memory should be increased where available
    # 8GiB will allow a cloud with a few micro instances
    cloud_opts_mem: "-Xmx1g"
    midonet_cassandra_heap: 1g
    midonet_cassandra_heapnew: 400m
    midonet_zookeeper_heap: 512m
    midonet_cluster_heap: 512m
    midonet_midolman_heap: 512m
    
    # If using EDGE then br0 must be configured and these
    # ip address ranges should be updated
    edge_private_ip_range: 192.168.254.150-192.168.254.199
    edge_public_ip_range: 192.168.254.200-192.168.254.249
    
    # If using VPCMIDO these defaults will work where available
    vpcmido_public_ip_range: 192.168.254.150-192.168.254.250
    vpcmido_public_ip_cidr: 192.168.254.128/25
    
  children:
    ceph: {}
    cloud:
      hosts:
        ciab:
    console:
      hosts:
        ciab:
    node:
      hosts:
        ciab:
    zone:
      hosts:
        ciab:

